on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install flask
          pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
          
          - run: python --version
      - uses: actions/checkout@v3
